### ISSUE TITLE
Fehlermeldung beim Slash in instances verbessern

### ISSUE THREAD

**Issue by kulagins** [hu-macsy/simexpal#124]
Wenn man in den Namen der instances ein Slash ("/") hat, dann ist die Fehlermeldung nicht sehr hilfreich. 

### Beispiel:
**experiments.yml**
```
instances:
  - repo: local
    items:
     - name: 'trees'
     - name: 'random-trees/random'
instdir: "data"

[...]
```
**Fehlermeldung:**

```
Traceback (most recent call last):
  File "/home/kulagins/anaconda3/bin/simex", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/kulagins/workspace/simexpal/simexpal/scripts/simex", line 971, in <module>
    main_args.cmd(main_args)
  File "/home/kulagins/workspace/simexpal/simexpal/scripts/simex", line 702, in do_experiments_launch
    submit_to_launcher(cfg, launcher_runs)
  File "/home/kulagins/workspace/simexpal/simexpal/scripts/simex", line 700, in submit_to_launcher
    launcher.submit(cfg, run)
  File "/home/kulagins/workspace/simexpal/simexpal/simexpal/launch/fork.py", line 6, in submit
    if not common.lock_run(run):
  File "/home/kulagins/workspace/simexpal/simexpal/simexpal/launch/common.py", line 27, in lock_run
    lockfd = os.open(run.aux_file_path('lock'),
FileNotFoundError: [Errno 2] No such file or directory: '/home/kulagins/workspace/tree-scheduler-refactored/aux/CP-EX-CP/random_trees/20_children.lock'

```
Es wäre hilfreicher, wenn die ".lock"-Datei nicht erwähnt wäre und eine Erklärung zu den nicht erlaubten Zeichen bei instances ausgegeben wäre.

**Comment by bernlu** [comment]
We should add a `subdir` key for each `repo` under `instances`:
Example:
```yml
instdir: 'data'
instances:
  - repo: local
    subdir: 'random-trees'
    items:
    - name: 'randomA'
    - name: 'randomB'
  - repo: local
    items:
    - name: 'treeA'
    - name: 'treeB'
```

file locations:
```
data/
  random-trees/
    randomA
    randomB
  treeA
  treeB
```
