### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by angriman** [hu-macsy/simexpal#5]
When running a considerable amount of experiments, the script crashed because of "too many open files". Probably, a call to `close()` is missing somewhere.

Full error output here:
```Traceback (most recent call last):                                                                     
  File "/home/angriman/.local/bin/simex", line 7, in <module>                          
    exec(compile(f.read(), __file__, 'exec')) 
  File "/home/angriman/projects/simexpal/scripts/simex", line 447, in <module>
    do_main()                                                                                       
  File "/home/angriman/projects/simexpal/scripts/simex", line 47, in do_main
    do_experiments(args)                                                                               
  File "/home/angriman/projects/simexpal/scripts/simex", line 199, in do_experiments 
    do_experiments_launch(args)                                                                        
  File "/home/angriman/projects/simexpal/scripts/simex", line 285, in do_experiments_launch 
    submit_to_launcher(cfg, sel)                                                                    
  File "/home/angriman/projects/simexpal/scripts/simex", line 283, in submit_to_launcher               
    launcher.submit(config, run)                                                                    
  File "/home/angriman/projects/simexpal/simexpal/launch/fork.py", line 12, in submit                  
    common.invoke_run(run)                                                                             
  File "/home/angriman/projects/simexpal/simexpal/launch/common.py", line 144, in invoke_run
    stdout=stdout, stderr=subprocess.PIPE)                                                   
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__                       
    restore_signals, start_new_session)                                                           
  File "/usr/lib/python3.6/subprocess.py", line 1234, in _execute_child        
    errpipe_read, errpipe_write = os.pipe()                                                      
OSError: [Errno 24] Too many open files
```

**Comment by duylethanh** [comment]
The error still exists. We should probably look into it some time

```
Traceback (most recent call last):
  File "/Users/duy/.local/bin/simex", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/duy/Projects/simexpal/scripts/simex", line 824, in <module>
    main_args.cmd(main_args)
  File "/Users/duy/Projects/simexpal/scripts/simex", line 630, in do_experiments_launch
    submit_to_launcher(cfg, sel)
  File "/Users/duy/Projects/simexpal/scripts/simex", line 628, in submit_to_launcher
    launcher.submit(cfg, run)
  File "/Users/duy/Projects/simexpal/simexpal/launch/fork.py", line 13, in submit
    common.invoke_run(manifest)
  File "/Users/duy/Projects/simexpal/simexpal/launch/common.py", line 269, in invoke_run
    (stderr_pipe, stderr) = os.pipe()
OSError: [Errno 24] Too many open files
```

**Comment by avdgrinten** [comment]
This means that we are leaking a file descriptor somewhere. Can you verify that all open() calls have corresponding close() calls?
